version: '2'
services:
    organiseit-app:
        image: organiseit
        external_links:
            - organiseit-mysql:mysql
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/organiseit?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    organiseit-mysql:
        extends:
            file: mysql.yml
            service: organiseit-mysql
